# ── Base: Java 17 (required for PySpark) on Ubuntu Jammy ──────────────────
FROM eclipse-temurin:17-jre-jammy

ENV PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive \
    SPARK_MASTER=local[2] \
    JAVA_HOME=/opt/java/openjdk \
    MLFLOW_TRACKING_URI=file:///app/mlruns \
    TRAIN_MAX_ROWS=40000 \
    SPARK_DRIVER_MEMORY=400m \
    SPARK_SHUFFLE_PARTITIONS=2 \
    SPARK_UI_ENABLED=false \
    # Render injects PORT; default to 8000 locally
    PORT=8000

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python deps first (layer cache)
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy application code
COPY src ./src
COPY app.py .
COPY static ./static
COPY scripts ./scripts

# Copy flood data (needed if training inside container)
COPY ["flood data", "./flood data"]

# Copy pre-trained model so Render doesn't need to train on startup
# (models/spark_pipeline is generated by src/train.py locally)
COPY models ./models

# Copy existing MLflow run metadata (optional — for /health model_loaded check)
COPY mlruns ./mlruns

RUN mkdir -p mlruns models

EXPOSE 8000

# start.py checks SKIP_TRAIN=1 → skips training, starts uvicorn on $PORT
CMD ["python3", "scripts/start.py"]
